spring:
  mvc:
    servlet:
      load-on-startup: 1 # 设置为启动服务器时初始化

  web:
    # 静态资源处理配置
    resources:
      add-mappings: true # 启用默认静态资源处理, 默认为true
      cache:
        cachecontrol:
          max-age: 3600 # 缓存响应时间, 单位为秒
      chain:
        enabled: true # 启用资源链, 默认为false
        cache: true # 启用资源链缓存, 默认为true
        compressed: true # 启用压缩资源, 默认为false
      static-locations: classpath:/static/ # 设置静态目录

  # thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/  # 指定前缀
    suffix: .html # 指定后缀
    check-template-location: true  # 检查模板路径是否存在
    cache: false  # 是否缓存: 开发模式下设置为false，避免改了模板还要重启服务器; 线上设置为true，可以提高性能。
    mode: HTML

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: zrzhuo
    password: 123456
    # 配置连接池, 这里使用hikari连接池
    hikari:
      pool-name: DateHikariCP # 名称
      minimum-idle: 5 # 最小空闲连接数
      idle-timeout: 600000 # 空闲连接最大存活时间
      maximum-pool-size: 10 # 最大连接数
      auto-commit: true # 开启自动提交
      max-lifetime: 1800000 # 连接最大存活时间
      connection-timeout: 30000 # 连接超时时间
      connection-test-query: SELECT 1 # 测试连接是否可用的查询语句

  # redis配置
  redis:
    host: localhost # 主机
    port: 6379 # 端口号
    database: 0 # 默认数据库
    timeout: 10000 # 超时时间
    # 连接池配置
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲连接数
        min-idle: 5 # 最小空闲连接数
        max-wait: 1000ms # 连接的最大等待时间


  # RabbitMQ配置
  rabbitmq:
    host: localhost # 服务器地址
    username: guest # 用户名
    password: guest # 密码
    virtual-host: / # 虚拟主机
    port: 5672  #端口
    listener:
      simple:
        concurrency: 10 # 消费者最小数量
        max-concurrency: 10 # 消费者最大数量
        prefetch: 1 # 限制消费者每次只处理一条消息，处理完再继续下一条消息
        auto-startup: true # 启动时是否默认启动容器，默认true
        default-requeue-rejected: true # 消息被拒绝时重新进入队列
    template:
      retry: # 重试
        enabled: true # 开启重试，默认false
        initial-interval: 1000ms # 重试时间，默认1000ms
        max-attempts: 3 # 重试最大次数，默认3次
        max-interval: 10000ms # 重试最大间隔时间，默认10000ms
        multiplier: 1 # 重试的间隔乘数。例如为2时，第一次等10s，第二次等20s，第三次等40s

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # Mapper映射文件的路径
  configuration:
    map-underscore-to-camel-case: true # 开启"下划线字段名"与"驼峰属性名"的映射
